# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/h1zzyy/Desktop/misis2026s-25-04-yucel-y-n/misis2026s-25-04-yucel-y-n

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/h1zzyy/Desktop/misis2026s-25-04-yucel-y-n/misis2026s-25-04-yucel-y-n

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/h1zzyy/Desktop/misis2026s-25-04-yucel-y-n/misis2026s-25-04-yucel-y-n/CMakeFiles /Users/h1zzyy/Desktop/misis2026s-25-04-yucel-y-n/misis2026s-25-04-yucel-y-n//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/h1zzyy/Desktop/misis2026s-25-04-yucel-y-n/misis2026s-25-04-yucel-y-n/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named complex

# Build rule for target.
complex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 complex
.PHONY : complex

# fast build rule for target.
complex/fast:
	$(MAKE) $(MAKESILENT) -f prj.labs/complex/CMakeFiles/complex.dir/build.make prj.labs/complex/CMakeFiles/complex.dir/build
.PHONY : complex/fast

#=============================================================================
# Target rules for targets named rational

# Build rule for target.
rational: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rational
.PHONY : rational

# fast build rule for target.
rational/fast:
	$(MAKE) $(MAKESILENT) -f prj.labs/rational/CMakeFiles/rational.dir/build.make prj.labs/rational/CMakeFiles/rational.dir/build
.PHONY : rational/fast

#=============================================================================
# Target rules for targets named arrayd

# Build rule for target.
arrayd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arrayd
.PHONY : arrayd

# fast build rule for target.
arrayd/fast:
	$(MAKE) $(MAKESILENT) -f prj.labs/arrayd/CMakeFiles/arrayd.dir/build.make prj.labs/arrayd/CMakeFiles/arrayd.dir/build
.PHONY : arrayd/fast

#=============================================================================
# Target rules for targets named arrayd_test

# Build rule for target.
arrayd_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arrayd_test
.PHONY : arrayd_test

# fast build rule for target.
arrayd_test/fast:
	$(MAKE) $(MAKESILENT) -f prj.test/CMakeFiles/arrayd_test.dir/build.make prj.test/CMakeFiles/arrayd_test.dir/build
.PHONY : arrayd_test/fast

#=============================================================================
# Target rules for targets named arrayt_test

# Build rule for target.
arrayt_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arrayt_test
.PHONY : arrayt_test

# fast build rule for target.
arrayt_test/fast:
	$(MAKE) $(MAKESILENT) -f prj.test/CMakeFiles/arrayt_test.dir/build.make prj.test/CMakeFiles/arrayt_test.dir/build
.PHONY : arrayt_test/fast

#=============================================================================
# Target rules for targets named bitsetd_profiler

# Build rule for target.
bitsetd_profiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bitsetd_profiler
.PHONY : bitsetd_profiler

# fast build rule for target.
bitsetd_profiler/fast:
	$(MAKE) $(MAKESILENT) -f prj.test/CMakeFiles/bitsetd_profiler.dir/build.make prj.test/CMakeFiles/bitsetd_profiler.dir/build
.PHONY : bitsetd_profiler/fast

#=============================================================================
# Target rules for targets named bitsetd_test

# Build rule for target.
bitsetd_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bitsetd_test
.PHONY : bitsetd_test

# fast build rule for target.
bitsetd_test/fast:
	$(MAKE) $(MAKESILENT) -f prj.test/CMakeFiles/bitsetd_test.dir/build.make prj.test/CMakeFiles/bitsetd_test.dir/build
.PHONY : bitsetd_test/fast

#=============================================================================
# Target rules for targets named dio_test

# Build rule for target.
dio_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dio_test
.PHONY : dio_test

# fast build rule for target.
dio_test/fast:
	$(MAKE) $(MAKESILENT) -f prj.test/CMakeFiles/dio_test.dir/build.make prj.test/CMakeFiles/dio_test.dir/build
.PHONY : dio_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... arrayd"
	@echo "... arrayd_test"
	@echo "... arrayt_test"
	@echo "... bitsetd_profiler"
	@echo "... bitsetd_test"
	@echo "... complex"
	@echo "... dio_test"
	@echo "... rational"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

