add_executable(arrayd_test arrayd_test.cpp)
target_link_libraries(arrayd_test arrayd)

add_executable(arrayt_test arrayt_test.cpp)
target_link_libraries(arrayt_test arrayt)

add_executable(bitsetd_profiler bitsetd_profiler.cpp)
target_link_libraries(bitsetd_profiler bitsetd)

add_executable(bitsetd_test bitsetd_test.cpp)
target_link_libraries(bitsetd_test bitsetd)

add_executable(dio_test dio_test.cpp)
target_link_libraries(dio_test dio)
